---
# Useful walk-throughs...
#     https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works
#     https://blog.dennisokeeffe.com/blog/2021-08-08-pytest-with-github-actions
# Thanks to Pallets/flask for a useful test.yaml template...
#     https://github.com/pallets/flask/blob/main/.github/workflows/tests.yaml
#
name: Tests
on:
  push:
    branches:
      - master
      - '*.x'
    paths-ignore:
      - 'sphinx-doc/**'
      - '*.md'
      - '*.rst'
  pull_request:
    branches:
      - master
      - '*.x'
    paths-ignore:
      - 'sphinx-doc/**'
      - '*.md'
      - '*.rst'

env:
    FORCE_COLOR: 1

jobs:
  tests:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - {name: Linux, python: '3.10', os: ubuntu-latest, pytest: py310}
          - {name: Windows, python: '3.10', os: windows-latest, pytest: py310}
          - {name: Mac, python: '3.10', os: macos-latest, pytest: py310}
          - {name: '3.11-dev', python: '3.11-dev', os: ubuntu-latest, pytest: py311}
          - {name: '3.9', python: '3.9', os: ubuntu-latest, pytest: py39}
          - {name: '3.8', python: '3.8', os: ubuntu-latest, pytest: py38}
          - {name: '3.7', python: '3.7', os: ubuntu-latest, pytest: py37}
          - {name: '3.6', python: '3.6', os: ubuntu-latest, pytest: py36}
          - {name: 'PyPy', python: 'pypy-3.7', os: ubuntu-latest, pytest: pypy37}
          - {name: 'ciscoconfparse Minimum Versions', python: '3.10', os: ubuntu-latest}
          - {name: 'ciscoconfparse Development Versions', python: '3.7', os: ubuntu-latest}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: update pip
        run: |
          python -m pip install -U pip
          pip install -U wheel
          pip install -U poetry==1.1.11
          pip install -U poetry-core==1.0.7
      - name: get pip cache dir
        id: pip-cache
        run: echo "::set-output name=dir::$(pip cache dir)"
      - name: cache pip
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: pip|${{ runner.os }}|${{ matrix.python }}|${{ hashFiles('pyproject.toml') }}|${{ hashFiles('requirements.txt') }}
      - run: pip install pytest==6.2.5
      - run: pip install -r requirements.txt
      - run: make test
